### PR TITLE
HAD-2680: Adds click handler for empty rows.

### PR DESCRIPTION
**Pull request by vinayakpatil**

### CODE REVIEW

**Comment by gregtalarico** [comment]
this looks good. just adjust that method name

**Comment by vinayakpatil** [comment]
@talarico43 Added separate click handler for empty rows, thanks!

**Comment by gregtalarico** [comment]
:+1:

**Comment by vinayakpatil** [comment]
@talarico43  Since you are the Collaborator, you will have to merge this :)

**Pull request merged**
